app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")) ,
    path("catalog/", include("goods.urls")),
    path("user/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path 
from . import views

app_name = "goods"


urlpatterns = [
    path("serch", views.catalog, name="search"),
    path("<slug:catalog_slug>", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product")
]

main/urls.py
from django.urls import path 
from . import views
app_name = "main"


urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.blog, name="blog"),
]

users/urls.py
from django.urls import path 
from users import views 

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout")
]

goods/models.py
from django.db import models

# Create your models here.


class Categories(models.Model):
    name = models.CharField(max_length = 150, unique = False, verbose_name="Категория")
    slug = models.SlugField(max_length = 150, unique = False, verbose_name="URL")

    class Meta:
        db_table = "category"
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ("id",)

    def __str__(self):
        return self.name 


class Products(models.Model):
    name = models.CharField(max_length = 150, unique=False, blank = False, verbose_name = "Название")
    slug = models.SlugField(max_length = 150, unique=False, blank = False, verbose_name = "URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="goods_images", null = True, blank=True,verbose_name="изображение")
    price = models.DecimalField(default = 0.00, max_digits=7, decimal_places=2, verbose_name = "цена")
    quantity = models.PositiveIntegerField(default = 0, verbose_name = "количество")
    category = models.ForeignKey(to=Categories, on_delete = models.CASCADE, verbose_name = "Категория")

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return self.name
    
    def id_display(self):
        return f"{self.id:05}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
# Create your models here.


class User(AbstractUser):

    image = models.ImageField(upload_to="image_users", blank = True, null = True)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

users/forms.py
from django import forms 
from .models import User 
from django.contrib.auth.forms import AuthenticationForm # Используется только для Логина тоесть не создаёт нового пользователя
from django.contrib.auth.forms import UserCreationForm   # Используется только для Регистрации и создаёт нового пользователя


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(label= "Имя пользователя", widget=forms.TextInput(attrs={"autofocus": True,
                                                                                        "class":"form-control",
                                                                                        "placeholder": "Ваше имя"}))
    password = forms.CharField(label = "Пароль", widget=forms.PasswordInput(attrs={"authocomplete":"current-password",
                                                                                   "class":"form-control",
                                                                                   "placeholder":"Ваш пароль"}))
    class Meta:
        model = User
        fields = ["username", "password"]
        
    
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    username = forms.CharField()
    password1 = forms.CharField()
    password2 =forms.CharField()

goods/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Products
from django.core.paginator import Paginator
from django.utils.http import urlencode
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, SearchHeadline
# Create your views here.


def catalog(request, catalog_slug=None):


    order_by1 = request.GET.get("order_by", None)
    on_sale = request.GET.get("on_sale", None)
    query = request.GET.get("q", None)
    current_slug = catalog_slug
    print(query)
    # print(order_by1)
    # print(on_sale)

    if catalog_slug == 'all':
        goods = Products.objects.all()
    elif query:
        if query.isdigit() and len(query) <= 5:
            goods = Products.objects.filter(id = int(query))
        else:
            vector = SearchVector('name', 'description')
            query  = SearchQuery(query)
            goods = Products.objects.annotate(rank=SearchRank(vector, query)).filter(rank__gt=0).order_by('-rank')
            # Подсветка поисковых слов
            goods = goods.annotate(headline_name=SearchHeadline("name", query, start_sel = '<span style="background-color:yellow;">', stop_sel="</span>"))
            goods = goods.annotate(headline_desc=SearchHeadline("description", query, start_sel = '<span style="background-color:yellow;">', stop_sel="</span>"))

            
            

    else:
        goods = get_list_or_404(Products.objects.filter(category__slug = catalog_slug))

    if order_by1 and order_by1 != "default":
        print("11")
        goods = goods.order_by(order_by1)
    if on_sale:
        
        goods = goods.filter(price__lt=200)

    # get_page = 1
    # if request.method == "GET":
    #     if request.GET.get('page'):
    #         get_page = request.GET.get('page', 1)

    get_page = request.GET.get('page', 1)

    get_request = urlencode(request.GET.dict())
    print(get_request)
    paginator = Paginator(goods, 3)
    curent_page = paginator.page(get_page)

    return render(request, "goods/catalog.html", {"goods": curent_page, "current_slug": current_slug, "get_request": get_request})

    


def product(request, product_slug):

    product = Products.objects.get(slug = product_slug)

    return render(request, "goods/product.html", {"product": product})

users/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegisterForm
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
#from django.contrib import lo
# Create your views here.


def login(request):
    
    messages.success(request, "Успешно вошли")
    # #ip = request.META.get("HTTP_X_FORWARDED_FOR")
    # ip = request.META.get("REMOTE_ADDR")
    # print(ip)

    form = UserLoginForm()
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        print("yes1")
        if form.is_valid():
            print("yes")
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            print(user)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("main:index"))
    else:
        form


    return render(request, "users/login.html", context={"form": form})

def registration(request):

    messages.success(request, "Успешно зарегестрировались")

    form = UserRegisterForm() 

    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse("users:login"))
    else:
        form

    return render(request, "users/registration.html", context={"form":form})

def profile(request):
    return render(request, "users/profile.html")

def logout(request):
    auth.logout(request)
    return redirect(reverse("users:login"))
    ...#return render(request, "users/")

templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}
{% block content %}

<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>

        <form action="{% if request.GET.q %}{% url "goods:search" %}{% else %}{% url "goods:index" current_slug %}"{% endif %} method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                {% if request.GET.q %}
                <input type="hidden" name="q" value="{{request.GET.q}}"> 
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">
                    Товары по акции
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %} >
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" {% if request.GET.order_by == "price" %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" {% if request.GET.order_by == "-price" %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>



    {% for i in goods %}
    
    <!-- Карта товара -->
    <div class="col-lg-4 col-md-6 p-4">
        <div class="card border-primary rounded custom-shadow">
            <div class="card-body">
                {% if i.image %}
                    <img src="{{i.image.url}}" class="card-img-top" alt="...">
                {% endif %}
                <a href="{% url "goods:product" i.slug %}">
                    {% if i.headline_name %}
                    {% autoescape off %}
                        {{i.headline_name}}
                    {% endautoescape %}
                    {% else %}
                        <p class="card-title">{{i.name}}</p>
                    {% endif %}    
                </a>

                {% if i.headline_desc %}
                    {% autoescape off %}
                        {{i.headline_desc}}
                    {% endautoescape %}
                {% else %}
                    <p class="card-text text-truncate">{{i.description}}</p>
                {% endif %}  

                <p class="product_id">id:{{i.id_display}} </p>
                <div class="d-flex justify-content-between">
                    
                    <p><strong>{{i.price}} $</strong></p>
                    <span class="badge bg-warning text-dark">Скидка 10.00 %</span>
                    <!-- <p><strong>100.00 $</strong></p> -->
                    <a href="#" class="btn add-to-cart">
                        <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                            width="32" height="32">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    

</div>


<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">


            <!-- если в ссылку обыную добавить знак ? он автоматически станет get запросом таким образом мы можемь настроить пагинацию очень легко на странцие href = "?page={{i}}" -->

            <!--Если в URL добавить знак вопроса ?, то все параметры, которые идут после него, будут восприниматься как GET-параметры. -->


            <!--Если страница не начальная значит кнопку включаем отвечающию за предыдущию страницу -->
            <li class="page-item {% if not goods.has_previous %}disabled{% endif %}">

                <!--Если страница есть значит добавляем url адрес со страницой -данная страница -->
              <a class="page-link" href="{% if goods.has_previous %}?{% change_params page=product.previous_page_number %}{% else %} # {% endif %} ">Преведущяя</a>
              {% comment %} {% url "goods:prod_slug"  url_page  product.previous_page_number %} {% endcomment %}
              
              
            
            </li>


            {% for i in goods.paginator.page_range %} {% comment %} <!-- product.number текущая страница  -->  {% url "goods:prod_slug" url_page i %} {% endcomment %}
                <li class="page-item {% if goods.number == i %} active {% endif %} "><a class="page-link" href="?{% change_params page=i %}">{{i}}</a></li> 
            {% endfor %} 

            

            <li class="page-item {% if not goods.has_next %}disabled{% endif %}">

                <a class="page-link" href="{% if goods.has_next %}?{% change_params page=goods.next_page_number%}{% else %} # {% endif %} ">Следуйщая</a>
                
                
            </li>
        </div>
    </ul>
</nav>

{% endblock content %}

templates/goods/product.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                {% if product.image %}
                    <img src="{{product.image.url}}">
                
                {% endif %}
                
                   
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">id: 002654</p>
            </div>
            <!-- Увеличить изображение в модальном окне -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            {% comment %} <img src="{{product.image.url}}" {% endcomment %}
                            {% if product.image %}
                                <img src="{{product.image.url}}">
                            {% else %}

                            {% endif %}
                            
                                
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Описание товара -->
        <div class="card-body">
            <p class="card-text">Цена: <strong>{{product.price}} $</strong></p>
            <h5 class="card-title">{{product.name}}</h5>
            <p class="card-text">{{product.description}}</p>
            <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
        </div>
    </div>
</div>

{% endblock content %}