app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")) ,
    path("catalog/", include("goods.urls")),
    path("user/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path 
from . import views

app_name = "goods"


urlpatterns = [
    path("serch", views.catalog, name="search"),
    path("<slug:catalog_slug>", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product")
]

main/urls.py
from django.urls import path 
from . import views
app_name = "main"


urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.blog, name="blog"),
]

users/urls.py
from django.urls import path 
from users import views 

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout")
]

goods/models.py
from django.db import models

# Create your models here.


class Categories(models.Model):
    name = models.CharField(max_length = 150, unique = False, verbose_name="Категория")
    slug = models.SlugField(max_length = 150, unique = False, verbose_name="URL")

    class Meta:
        db_table = "category"
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ("id",)

    def __str__(self):
        return self.name 


class Products(models.Model):
    name = models.CharField(max_length = 150, unique=False, blank = False, verbose_name = "Название")
    slug = models.SlugField(max_length = 150, unique=False, blank = False, verbose_name = "URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="goods_images", null = True, blank=True,verbose_name="изображение")
    price = models.DecimalField(default = 0.00, max_digits=7, decimal_places=2, verbose_name = "цена")
    quantity = models.PositiveIntegerField(default = 0, verbose_name = "количество")
    category = models.ForeignKey(to=Categories, on_delete = models.CASCADE, verbose_name = "Категория")

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return self.name
    
    def id_display(self):
        return f"{self.id:05}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
# Create your models here.


class User(AbstractUser):

    image = models.ImageField(upload_to="image_users", blank = True, null = True)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

users/forms.py
from django import forms 
from .models import User 
from django.contrib.auth.forms import AuthenticationForm # Используется только для Логина тоесть не создаёт нового пользователя
from django.contrib.auth.forms import UserCreationForm   # Используется только для Регистрации и создаёт нового пользователя


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(label= "Имя пользователя", widget=forms.TextInput(attrs={"autofocus": True,
                                                                                        "class":"form-control",
                                                                                        "placeholder": "Ваше имя"}))
    password = forms.CharField(label = "Пароль", widget=forms.PasswordInput(attrs={"authocomplete":"current-password",
                                                                                   "class":"form-control",
                                                                                   "placeholder":"Ваш пароль"}))
    class Meta:
        model = User
        fields = ["username", "password"]
        
    
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    username = forms.CharField()
    password1 = forms.CharField()
    password2 =forms.CharField()

goods/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Products
from django.core.paginator import Paginator
from django.utils.http import urlencode
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, SearchHeadline
# Create your views here.


def catalog(request, catalog_slug=None):


    order_by1 = request.GET.get("order_by", None)
    on_sale = request.GET.get("on_sale", None)
    query = request.GET.get("q", None)
    current_slug = catalog_slug
    print(query)
    # print(order_by1)
    # print(on_sale)

    if catalog_slug == 'all':
        goods = Products.objects.all()
    elif query:
        if query.isdigit() and len(query) <= 5:
            goods = Products.objects.filter(id = int(query))
        else:
            vector = SearchVector('name', 'description')
            query  = SearchQuery(query)
            goods = Products.objects.annotate(rank=SearchRank(vector, query)).filter(rank__gt=0).order_by('-rank')
            # Подсветка поисковых слов
            goods = goods.annotate(headline_name=SearchHeadline("name", query, start_sel = '<span style="background-color:yellow;">', stop_sel="</span>"))
            goods = goods.annotate(headline_desc=SearchHeadline("description", query, start_sel = '<span style="background-color:yellow;">', stop_sel="</span>"))

            
            

    else:
        goods = get_list_or_404(Products.objects.filter(category__slug = catalog_slug))

    if order_by1 and order_by1 != "default":
        print("11")
        goods = goods.order_by(order_by1)
    if on_sale:
        
        goods = goods.filter(price__lt=200)

    # get_page = 1
    # if request.method == "GET":
    #     if request.GET.get('page'):
    #         get_page = request.GET.get('page', 1)

    get_page = request.GET.get('page', 1)

    get_request = urlencode(request.GET.dict())
    print(get_request)
    paginator = Paginator(goods, 3)
    curent_page = paginator.page(get_page)

    return render(request, "goods/catalog.html", {"goods": curent_page, "current_slug": current_slug, "get_request": get_request})

    


def product(request, product_slug):

    product = Products.objects.get(slug = product_slug)

    return render(request, "goods/product.html", {"product": product})

users/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegisterForm
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
#from django.contrib import lo
# Create your views here.


def login(request):
    
    messages.success(request, "Успешно вошли")
    # #ip = request.META.get("HTTP_X_FORWARDED_FOR")
    # ip = request.META.get("REMOTE_ADDR")
    # print(ip)

    form = UserLoginForm()
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        print("yes1")
        if form.is_valid():
            print("yes")
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            print(user)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("main:index"))
    else:
        form


    return render(request, "users/login.html", context={"form": form})

def registration(request):

    messages.success(request, "Успешно зарегестрировались")

    form = UserRegisterForm() 

    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse("users:login"))
    else:
        form

    return render(request, "users/registration.html", context={"form":form})

def profile(request):
    return render(request, "users/profile.html")

def logout(request):
    auth.logout(request)
    return redirect(reverse("users:login"))
    ...#return render(request, "users/")

templates/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>Home</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="index.html">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "users:login" %}">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "users:profile" %}">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "users:logout" %}">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search" action="{% url "goods:search" %}" method="GET">
                        <input class="form-control me-2" name='q' type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% goods_category as categories %}
                        {% for category in categories %}
                        
                        <li><a class="dropdown-item text-white" href="{% url "goods:index" category.slug %}">{{category.name}}</a></li>


                        {% endfor %}
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="deps/icons/basket2-fill.svg" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="deps/icons/trash3-fill.svg"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </section>
    
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>