app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")) ,
    path("catalog/", include("goods.urls")),
    path("user/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path 
from . import views

app_name = "goods"


urlpatterns = [
    path("serch", views.catalog, name="search"),
    path("<slug:catalog_slug>", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product")
]

main/urls.py
from django.urls import path 
from . import views
app_name = "main"


urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.blog, name="blog"),
]

users/urls.py
from django.urls import path 
from users import views 

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout")
]

goods/models.py
from django.db import models

# Create your models here.


class Categories(models.Model):
    name = models.CharField(max_length = 150, unique = False, verbose_name="Категория")
    slug = models.SlugField(max_length = 150, unique = False, verbose_name="URL")

    class Meta:
        db_table = "category"
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ("id",)

    def __str__(self):
        return self.name 


class Products(models.Model):
    name = models.CharField(max_length = 150, unique=False, blank = False, verbose_name = "Название")
    slug = models.SlugField(max_length = 150, unique=False, blank = False, verbose_name = "URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="goods_images", null = True, blank=True,verbose_name="изображение")
    price = models.DecimalField(default = 0.00, max_digits=7, decimal_places=2, verbose_name = "цена")
    quantity = models.PositiveIntegerField(default = 0, verbose_name = "количество")
    category = models.ForeignKey(to=Categories, on_delete = models.CASCADE, verbose_name = "Категория")

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return self.name
    
    def id_display(self):
        return f"{self.id:05}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
# Create your models here.


class User(AbstractUser):

    image = models.ImageField(upload_to="image_users", blank = True, null = True)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

users/forms.py
from django import forms 
from .models import User 
from django.contrib.auth.forms import AuthenticationForm # Используется только для Логина тоесть не создаёт нового пользователя
from django.contrib.auth.forms import UserCreationForm   # Используется только для Регистрации и создаёт нового пользователя


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(label= "Имя пользователя", widget=forms.TextInput(attrs={"autofocus": True,
                                                                                        "class":"form-control",
                                                                                        "placeholder": "Ваше имя"}))
    password = forms.CharField(label = "Пароль", widget=forms.PasswordInput(attrs={"authocomplete":"current-password",
                                                                                   "class":"form-control",
                                                                                   "placeholder":"Ваш пароль"}))
    class Meta:
        model = User
        fields = ["username", "password"]
        
    
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    username = forms.CharField()
    password1 = forms.CharField()
    password2 =forms.CharField()

goods/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Products
from django.core.paginator import Paginator
from django.utils.http import urlencode
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, SearchHeadline
# Create your views here.


def catalog(request, catalog_slug=None):


    order_by1 = request.GET.get("order_by", None)
    on_sale = request.GET.get("on_sale", None)
    query = request.GET.get("q", None)
    current_slug = catalog_slug
    print(query)
    # print(order_by1)
    # print(on_sale)

    if catalog_slug == 'all':
        goods = Products.objects.all()
    elif query:
        if query.isdigit() and len(query) <= 5:
            goods = Products.objects.filter(id = int(query))
        else:
            vector = SearchVector('name', 'description')
            query  = SearchQuery(query)
            goods = Products.objects.annotate(rank=SearchRank(vector, query)).filter(rank__gt=0).order_by('-rank')
            # Подсветка поисковых слов
            goods = goods.annotate(headline_name=SearchHeadline("name", query, start_sel = '<span style="background-color:yellow;">', stop_sel="</span>"))
            goods = goods.annotate(headline_desc=SearchHeadline("description", query, start_sel = '<span style="background-color:yellow;">', stop_sel="</span>"))

            
            

    else:
        goods = get_list_or_404(Products.objects.filter(category__slug = catalog_slug))

    if order_by1 and order_by1 != "default":
        print("11")
        goods = goods.order_by(order_by1)
    if on_sale:
        
        goods = goods.filter(price__lt=200)

    # get_page = 1
    # if request.method == "GET":
    #     if request.GET.get('page'):
    #         get_page = request.GET.get('page', 1)

    get_page = request.GET.get('page', 1)

    get_request = urlencode(request.GET.dict())
    print(get_request)
    paginator = Paginator(goods, 3)
    curent_page = paginator.page(get_page)

    return render(request, "goods/catalog.html", {"goods": curent_page, "current_slug": current_slug, "get_request": get_request})

    


def product(request, product_slug):

    product = Products.objects.get(slug = product_slug)

    return render(request, "goods/product.html", {"product": product})

users/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegisterForm
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
#from django.contrib import lo
# Create your views here.


def login(request):
    
    messages.success(request, "Успешно вошли")
    # #ip = request.META.get("HTTP_X_FORWARDED_FOR")
    # ip = request.META.get("REMOTE_ADDR")
    # print(ip)

    form = UserLoginForm()
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        print("yes1")
        if form.is_valid():
            print("yes")
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            print(user)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("main:index"))
    else:
        form


    return render(request, "users/login.html", context={"form": form})

def registration(request):

    messages.success(request, "Успешно зарегестрировались")

    form = UserRegisterForm() 

    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse("users:login"))
    else:
        form

    return render(request, "users/registration.html", context={"form":form})

def profile(request):
    return render(request, "users/profile.html")

def logout(request):
    auth.logout(request)
    return redirect(reverse("users:login"))
    ...#return render(request, "users/")

templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                
                
                <h2 class="text-center mb-4">Авторизация</h2>
                
                

                <form action="{% url "users:login" %}" method = "POST">
                    {{form.non_field_errors}}
                    
                    {% csrf_token %}
                    
                    {% for i in form %}
                    
                    
                        <div class="mb-3">
                            <label  class="form-label">{{i.label}}</label>
                            {{i}}
                        </div>
                    {% endfor %}
                        
                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url "users:registration" %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row mt-1">
        <div class="col-lg-2">
            <!-- Пустой блок на усмотрение -->
        </div>
        <div class="col-lg-10">
            <!-- Контент на странице -->
            <div class="row">
                <div class="container mt-5">
                    <div class="row">
                        <!-- Профиль с данными пользователя -->
                        <div class="col-md-5">
                            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                <h3 class="text-center mb-4">Профиль пользователя</h3>
                                <form>
                                    <div class="row">
                                        <div class="col-md-12 mb-3 text-center">
                                            <img src="{% static "deps/images/baseavatar.jpg" %}"
                                                alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                style="max-width: 150px;">
                                            <input type="file" class="form-control mt-3" id="avatar"
                                                accept="image/*">
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <label for="firstName" class="form-label">Имя*</label>
                                            <input type="text" class="form-control" id="firstName"
                                                placeholder="Введите ваше имя" value="" required>
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <label for="lastName" class="form-label">Фамилия*</label>
                                            <input type="text" class="form-control" id="lastName"
                                                placeholder="Введите вашу фамилию" value="" required>
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <label for="username" class="form-label">Имя пользователя*</label>
                                            <input type="text" class="form-control" id="username"
                                                placeholder="Введите ваше имя пользователя" value="" required>
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <label for="email" class="form-label">Email*</label>
                                            <input type="email" class="form-control" id="email"
                                                placeholder="Введите ваш email *youremail@example.com" value=""
                                                required>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-dark">Сохранить</button>
                                </form>
                            </div>
                        </div>
                        <!-- Корзина -->
                        <div class="col-md-7">
                            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="../orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                        <!-- Оформленные заказы -->
                        <div class="col-md-12">
                            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                <h3 class="text-center mb-4">Мои заказы</h3>
                                <!-- Разметка заказов -->
                                <div class="container">
                                    <div class="accordion" id="accordionExample">
                                        <div class="accordion-item">
                                            <h2 class="accordion-header" id="heading1">
                                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                                    Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                                </button>
                                            </h2>
                                            <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                                <div class="accordion-body">
                                                    <table class="table table-dark table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Товар</th>
                                                                <th>Количество</th>
                                                                <th>Цена</th>
                                                                <th>Общая стоимость</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                                <td>1</td>
                                                                <td>255.00 $</td>
                                                                <td>255.00 $</td>
                                                                
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                    <div class="d-flex justify-content-between">
                                                        <p><strong>Итого:</strong></p>
                                                        <p><strong>255.00 $</strong></p>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="accordion-item">
                                            <h2 class="accordion-header" id="heading2">
                                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                                    Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                                </button>
                                            </h2>
                                            <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                                <div class="accordion-body">
                                                    <table class="table table-dark table-hover">
                                                        <thead>
                                                            <tr>
                                                                <th>Товар</th>
                                                                <th>Количество</th>
                                                                <th>Цена</th>
                                                                <th>Общая стоимость</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td><a class="text-white" href="#">Стул офисный</a></td>
                                                                <td>2</td>
                                                                <td>30.00 $</td>
                                                                <td>60.00 $</td>
                                                                
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Закончилась разметка заказов -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/users/registration.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url "users:registration" %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name" name="first_name" velue="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}"
                                placeholder="Введите ваше имя" required>
                                {% if form.first_name.errors %}{{form.first_name.errors}}{% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name" velue="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"
                                placeholder="Введите вашу фамилию" required>
                                {% if form.last_name.errors %}{{form.last_name.errors}}{% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username" name="username" value="{% if form.username.value %}{{form.username.value}}{% endif %}"
                                placeholder="Введите ваше имя пользователя" required>
                                {% if form.username.errors %}{{form.username.errors}}{% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email" name="email" value="{% if form.email.value %}{{form.email.value}}{% endif %}"
                                placeholder="Введите ваш email" required>
                                {% if form.email.errors %}{{form.email.errors}}{% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1" name="password1" value="{% if form.password1.value %}{{form.password1.value}}{% endif %}"
                                placeholder="Введите пароль" required>
                                {% if form.password1.errors %}{{form.password1.errors}}{% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2" name="password2" value="{% if form.password2.value %}{{form.password2.value}}{% endif %}"
                                placeholder="Подтвердите пароль" required>
                                {% if form.password2.errors %}{{form.password2.errors}}{% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}